#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# Deploy Script - Generic for any environment
# ═══════════════════════════════════════════════════════════════════════════════
#
# This script:
# 1. Fetches configuration from AWS SSM Parameter Store
# 2. Generates .env.<environment> file with image tags
# 3. Pulls images from GHCR and starts containers
#
# Usage:
#   ./deploy.sh <environment>
#   IMAGE_TAG=abc123 ./deploy.sh staging
#   ./deploy.sh prod
#
# Environment variables:
#   IMAGE_TAG - Docker image tag to deploy (default: latest)
#
# Prerequisites:
#   - AWS CLI configured with proper permissions
#   - SSM parameters provisioned via: pnpm provision <environment>
#
# ═══════════════════════════════════════════════════════════════════════════════

set -e

# ───────────────────────────────────────────────────────────────────────────────
# Parse arguments
# ───────────────────────────────────────────────────────────────────────────────

ENVIRONMENT="${1:-staging}"
SSM_PATH="/city-guided/${ENVIRONMENT}"
IMAGE_TAG="${IMAGE_TAG:-latest}"

# GHCR images
GHCR_REPO="ghcr.io/elzinko/city-guided"
API_IMAGE="${GHCR_REPO}-api:${IMAGE_TAG}"
WEB_IMAGE="${GHCR_REPO}-web:${IMAGE_TAG}"

# Auto-detect AWS region from instance metadata (for EC2) or use default
if [ -z "$AWS_DEFAULT_REGION" ]; then
    # Try to get region from EC2 instance metadata
    TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" 2>/dev/null || true)
    if [ -n "$TOKEN" ]; then
        AWS_DEFAULT_REGION=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/placement/region 2>/dev/null || echo "eu-west-3")
    else
        AWS_DEFAULT_REGION="eu-west-3"
    fi
    export AWS_DEFAULT_REGION
fi
echo "🌍 AWS Region: ${AWS_DEFAULT_REGION}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCKER_DIR="$(dirname "$SCRIPT_DIR")"

cd "$DOCKER_DIR"

ENV_FILE=".env.${ENVIRONMENT}"

echo "╔════════════════════════════════════════════════════════╗"
echo "║         🚀 City-Guided Deployment                      ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""
echo "📋 Environment: ${ENVIRONMENT}"
echo "📦 SSM Path:    ${SSM_PATH}"
echo "📁 Config file: ${ENV_FILE}"
        echo ""

# ───────────────────────────────────────────────────────────────────────────────
# Fetch configuration from AWS SSM Parameter Store
# ───────────────────────────────────────────────────────────────────────────────

echo "📥 Fetching configuration from AWS SSM..."

# Check if AWS CLI is available
if ! command -v aws &> /dev/null; then
    echo "❌ AWS CLI not found!"
    echo "   Install: https://aws.amazon.com/cli/"
        exit 1
    fi
    
# Fetch all parameters for this environment
PARAMS=$(aws ssm get-parameters-by-path \
    --path "${SSM_PATH}" \
    --with-decryption \
    --query "Parameters[*].[Name,Value]" \
    --output text 2>/dev/null)

if [ -z "$PARAMS" ]; then
    echo "❌ No parameters found in SSM at ${SSM_PATH}"
    echo ""
    echo "   Did you run: pnpm provision ${ENVIRONMENT}"
    echo ""
    
    # Fallback: check if .env file exists
    if [ -f "$ENV_FILE" ]; then
        echo "⚠️  Using existing ${ENV_FILE} file"
    else
        exit 1
    fi
else
    # Generate .env file from SSM parameters
    echo "📝 Generating ${ENV_FILE} from SSM parameters..."
    
    # Create header
    cat > "$ENV_FILE" << EOF
# ═══════════════════════════════════════════════════════════════════════════════
# Generated by deploy.sh from AWS SSM Parameter Store
# Source: ${SSM_PATH}/*
# Generated at: $(date -Iseconds)
# ═══════════════════════════════════════════════════════════════════════════════

EOF

    # Parse SSM output and write to .env file
    echo "$PARAMS" | while IFS=$'\t' read -r name value; do
        # Extract variable name from full path (e.g., /city-guided/staging/SITE_DOMAIN -> SITE_DOMAIN)
        var_name=$(basename "$name")
        
        # Skip SECRET_ prefix variables from being written with prefix
        # (they're already stored with prefix in SSM for identification)
        echo "${var_name}=${value}" >> "$ENV_FILE"
    done

    # Add derived URLs and image configuration
    source "$ENV_FILE"
    cat >> "$ENV_FILE" << EOF

# Derived URLs
NEXT_PUBLIC_API_URL=https://${SITE_DOMAIN}/api
NEXT_PUBLIC_OSRM_URL=https://${SITE_DOMAIN}/osrm

# Docker images from GHCR
API_IMAGE=${API_IMAGE}
WEB_IMAGE=${WEB_IMAGE}

# Build metadata
APP_VERSION=${IMAGE_TAG}
APP_REPO_URL=https://github.com/elzinko/city-guided
EOF

    echo "✅ ${ENV_FILE} generated from SSM"
fi

echo ""
echo "📋 Configuration loaded:"
grep -E "^(SITE_DOMAIN|ENVIRONMENT|API_PORT|WEB_PORT|API_IMAGE|WEB_IMAGE)=" "$ENV_FILE" 2>/dev/null | sed 's/^/   /' || true
echo ""

# ───────────────────────────────────────────────────────────────────────────────
# Pull images from GHCR
# ───────────────────────────────────────────────────────────────────────────────

echo "🐳 Pulling images from GHCR..."
echo "   API: ${API_IMAGE}"
echo "   Web: ${WEB_IMAGE}"
echo ""

docker pull "${API_IMAGE}" || { echo "❌ Failed to pull API image"; exit 1; }
docker pull "${WEB_IMAGE}" || { echo "❌ Failed to pull Web image"; exit 1; }

echo "✅ Images pulled successfully"
echo ""

# ───────────────────────────────────────────────────────────────────────────────
# Start the environment
# ───────────────────────────────────────────────────────────────────────────────

echo "🚀 Starting ${ENVIRONMENT} environment..."
echo ""

# Use the generic start script
chmod +x "$SCRIPT_DIR/start.sh"
exec "$SCRIPT_DIR/start.sh" "$ENVIRONMENT"
