#!/usr/bin/env tsx
/**
 * SSM Cleanup Script
 * 
 * Remove obsolete variables from SSM Parameter Store
 * 
 * Usage:
 *   pnpm cleanup:ssm staging
 */

import { SSMClient, DeleteParameterCommand, GetParametersByPathCommand } from '@aws-sdk/client-ssm';
import chalk from 'chalk';
import {
  AWS_CONFIG,
  getSsmPath,
  type EnvironmentName,
} from '../constants.js';

const ssmClient = new SSMClient({ region: AWS_CONFIG.region });

// ═══════════════════════════════════════════════════════════════════════════════
// OBSOLETE VARIABLES
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Variables that should be removed from SSM:
 * - NGINX_*: We use Caddy now, not Nginx
 * - Variables generated dynamically by deploy.sh (should not be in SSM)
 * - SECRET_AWS_*: Auto-added by provision.ts, should not be in .env files
 * - *_CONTAINER_NAME: Generated by docker-compose
 * - *_IMAGE_TAG: Generated by deploy.sh
 */
const OBSOLETE_VARIABLES = [
  'NGINX_HTTP_PORT',
  'NGINX_HTTPS_PORT',
  'API_CONTAINER_NAME',
  'WEB_CONTAINER_NAME',
  'OSRM_CONTAINER_NAME',
  'API_IMAGE_TAG',
  'WEB_IMAGE_TAG',
  'API_LOG_LEVEL',
  // Add more obsolete variables here if needed
];

// ═══════════════════════════════════════════════════════════════════════════════
// CLEANUP
// ═══════════════════════════════════════════════════════════════════════════════

async function cleanupSsm(env: EnvironmentName): Promise<void> {
  console.log(chalk.bold.cyan('\n╔════════════════════════════════════════════════════════╗'));
  console.log(chalk.bold.cyan(`║         🧹 SSM Cleanup: ${env.toUpperCase()}                    ║`));
  console.log(chalk.bold.cyan('╚════════════════════════════════════════════════════════╝\n'));

  const ssmPath = getSsmPath(env);
  console.log(chalk.blue(`🔍 Scanning SSM: ${ssmPath}/*\n`));

  // Get all parameters
  const response = await ssmClient.send(
    new GetParametersByPathCommand({
      Path: ssmPath,
      Recursive: true,
    })
  );

  const parameters = response.Parameters || [];
  console.log(chalk.white(`   Found ${parameters.length} parameters in SSM\n`));

  // Find obsolete parameters
  const obsoleteParams = parameters.filter((param) => {
    const key = param.Name?.replace(`${ssmPath}/`, '') || '';
    return OBSOLETE_VARIABLES.includes(key);
  });

  if (obsoleteParams.length === 0) {
    console.log(chalk.green('✓ No obsolete variables found\n'));
    return;
  }

  console.log(chalk.yellow(`⚠️  Found ${obsoleteParams.length} obsolete variable(s):\n`));
  for (const param of obsoleteParams) {
    const key = param.Name?.replace(`${ssmPath}/`, '') || '';
    console.log(chalk.white(`   - ${key}`));
  }

  console.log(chalk.cyan('\n🗑️  Deleting obsolete variables...\n'));

  let deleted = 0;
  let errors = 0;

  for (const param of obsoleteParams) {
    try {
      await ssmClient.send(
        new DeleteParameterCommand({
          Name: param.Name,
        })
      );
      console.log(chalk.green(`   ✓ Deleted: ${param.Name?.replace(`${ssmPath}/`, '')}`));
      deleted++;
    } catch (error: any) {
      console.error(chalk.red(`   ✗ Failed to delete ${param.Name}: ${error.message}`));
      errors++;
    }
  }

  console.log(chalk.green(`\n✓ Cleanup complete: ${deleted} deleted, ${errors} errors\n`));
}

// ═══════════════════════════════════════════════════════════════════════════════
// MAIN
// ═══════════════════════════════════════════════════════════════════════════════

async function main() {
  const args = process.argv.slice(2);
  
  if (args.length < 1) {
    console.error(chalk.red('Usage: pnpm cleanup:ssm <environment>'));
    console.log(chalk.white('   Example: pnpm cleanup:ssm staging'));
    process.exit(1);
  }

  const env = args[0] as EnvironmentName;

  if (env !== 'staging' && env !== 'prod') {
    console.error(chalk.red(`Invalid environment: ${env}`));
    console.log(chalk.white('   Valid environments: staging, prod'));
    process.exit(1);
  }

  await cleanupSsm(env);
}

main().catch((error) => {
  console.error(chalk.red(`\n❌ Error: ${error.message}\n`));
  if (error.stack) {
    console.error(chalk.dim(error.stack));
  }
  process.exit(1);
});
